#!/usr/bin/expect -f

#set jump_machine "11.251.177.198"
set jump_machine "11.180.55.1"
#加密命令echo "ibase=16; $(echo "域账号密码" |xxd -ps -u)" |bc 结尾加P
set password "22405562582412693122143367178P"
set door_machine [lindex $argv 0]
set server [lindex $argv 1]
set token [lindex $argv 2]

spawn ssh -o ServerAliveInterval=30 ${door_machine}
set password "[exec dc -e ${password}]"
expect {
   "(yes/no)?" {
           send "yes\r"
           exp_continue
   }
   "*DomainPassword*" {
           send "${password}${token}\r"
           exp_continue
   }
   "*\\$" {}
}

send "ssh ${jump_machine} \r"
expect {
       "*passphrase*" {
               send "${password}\r"
               exp_continue
       }
       "*\\$" {}
}
send "sudo su serving\r"
expect "*password*" { send "${password}\r" }
expect "*\\$" { send "ssh ${server}\r"}
interact
