#!/usr/bin/python

import sys
import os

if __name__ == "__main__":
    pwd_dir = os.getcwd()
    argv_index = 1
    build_tool = ''
    if len(sys.argv) > 1 and sys.argv[1] == 'blade':
        build_tool = 'blade'
        argv_index = 2
    elif len(sys.argv) > 1 and sys.argv[1] == 'make':
        build_tool = 'make'
        argv_index = 2
    else:
        current_dir = pwd_dir
        while current_dir != '/':
            print current_dir
            if os.path.exists(current_dir + '/BLADE_ROOT'):
                break;
            current_dir = os.path.dirname(current_dir)

        if current_dir != '/':
            if os.path.exists(current_dir + '/retrieval2'):
                build_tool = './build.sh'
                os.chdir(current_dir + '/retrieval2')
            elif os.path.exists(current_dir + '/Ad_Servers'):
                build_tool = './build_git.sh'
                os.chdir(current_dir + '/Ad_Servers')
            elif os.path.exists(current_dir + '/src'):
                build_tool = './build.sh'
                os.chdir(current_dir + '/src')
            elif os.path.exists(current_dir + '/pub'):
                build_tool = 'make opt -j16'
                os.chdir(current_dir)
        else:
                os.chdir(pwd_dir)
                if os.path.exists(pwd_dir + '/build.sh'):
                    build_tool = './build.sh'
                else:
                    build_tool = 'make -j16'

    # Arguments parse
    arguments = ''
    for i in range(argv_index, len(sys.argv)):
        arguments += " " + sys.argv[i]

    # Exec command
    os.system(build_tool + arguments)
